import ToastWrapper from '@components/ToastWrapper'
import '@styles/globals.css'
import { Inter, Lato } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lato',
  display: 'swap',
})

export const metadata = {
  title: 'Pre-Approval App',
  description: 'Generated by Driv.ly',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${lato.variable}`}>
        <main className='min-h-screen bg-white font-inter'>
          <div className='flex flex-1 flex-col sm:px-4 md:px-6'>
            {children}
            <ToastWrapper />
          </div>
        </main>
      </body>
    </html>
  )
}

